### ISSUE TITLE
Functioning as per readme?

### ISSUE THREAD

**Issue by madhuravius** [godu/serverless#2]
Hey! 

I really want to use your plugin since it's brand new and support for SQS as an event trigger is in place.

When I follow your documentation instructions, I get the below error:

```
  Serverless Error ---------------------------------------

  Serverless plugin "serverless-offline-sqs" initialization errored: Unexpected identifier

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Issues:        forum.serverless.com

  Your Environment Information -----------------------------
     OS:                     darwin
     Node Version:           6.10.3
     Serverless Version:     1.29.2
```

I followed the above based on these instructions:

```
Then inside your project's serverless.yml file, add following entry to the plugins section before serverless-offline (and after serverless-webpack if presents): serverless-offline-sqs.

plugins:
  - serverless-webpack
  - serverless-offline-sqs
  - serverless-offline
```

**Comment by madhuravius** [comment]
I think my mistake was quite silly. I can't currently test (due to other breaking changes), but even though I was using the most recent version of serverless, I was specifying a older version ~1.26 (before SQS support) at the top of serverless.yml. I will try to test and will re-open this bug (or create a new issue) if I see it appear then.

**Comment by lagnat** [comment]
Just had this problem.  The issue is that the plugin uses async/await and you were probably using a node version that did not support it.
