### ISSUE TITLE
serverless-offline-sqs configuration issue

### ISSUE THREAD

**Issue by ossareh** [godu/serverless#5]
Hi there,

I've been playing with offline-sqs and I believe there is a code bug.

The specific line is: https://github.com/godu/serverless/blob/master/packages/serverless-offline-sqs/src/index.js#L38

When you create a queue in AWS there is no trailing '/' in the ARN; which this code expects.

```
$ aws sqs create-queue --queue-name funtimes
{
    "QueueUrl": "https://us-west-2.queue.amazonaws.com/<acct>/funtimes"
}

$ aws sqs get-queue-attributes --queue-url <url_above> --attribute-names QueueArn
{
    "Attributes": {
        "QueueArn": "arn:aws:sqs:us-west-2:<acct>:funtimes"
    }
}
```

Reading this code makes me think there should be a URL in the function sqs configurtion, however that is not in line with the [serverless docs on the matter](https://serverless.com/framework/docs/providers/aws/events/sqs/)

```
functions:
    funtimes:
        handler: src/funtimes.handler
        events:
            - sqs:
                arn: arn:aws:sqs:us-west-2:<acct>:funtimes
```

When I use this plugin I get the following error:

```
[1] (node:20757) UnhandledPromiseRejectionWarning: MissingRequiredParameter: Missing required key 'QueueName' in params
[1]     at ParamValidator.fail (/Users/ossareh/dev/src/code.famfi.co/mono/node_modules/serverless-offline-sqs/node_modules/aws-sdk/lib/param_validator.js:50:37)
[1]     at ParamValidator.validateStructure (/Users/ossareh/dev/src/code.famfi.co/mono/node_modules/serverless-offline-sqs/node_modules/aws-sdk/lib/param_validator.js:61:14)
[1]     at ParamValidator.validateMember (/Users/ossareh/dev/src/code.famfi.co/mono/node_modules/serverless-offline-sqs/node_modules/aws-sdk/lib/param_validator.js:88:21)
```

The config I have is pretty simple:

```
custom:
    servleress-offline-sqs:
        region: us-west-2 # without this we get a missing region related error
```

Also, it's not possible to use a slash in a queue name:

```
$ aws sqs create-queue --queue-name funtimes/method

An error occurred (InvalidParameterValue) when calling the CreateQueue operation: Can only include alphanumeric characters, hyphens, or underscores. 1 to 80 in length
```

One thought I had was to allow the user to specify the QueueName directly, you can see this here: https://github.com/ossareh/serverless/commit/8da4b4735f7080674f1867e98827dbddc94c191b - however before submitting this to you in a PR I wanted to make sure I'm not missing something obvious.

**Comment by ossareh** [comment]
@godu - hi there, any thought on this?

**Comment by godu** [comment]
@ossareh Hi,

You're right, the configuration process is weird. Adding a option should be the first strategy to resolve QueueName, then extract it from ARN if option is missing.

I'll fix extracting method to support `/` charactere.

Could you propose a PR to add QueueName option ?

**Comment by ossareh** [comment]
hey @godu - I have now submitted PR: #6

**Comment by godu** [comment]
@ossareh Hi, i publish a minor release with your modifications. Do you agree ?

**Comment by ossareh** [comment]
yes, absolutely

**Comment by ricardovf** [comment]
I have this problem too on the last version of this plugin and last version of serverless-offline...

MissingRequiredParameter: Missing required key 'QueueName' in params

Using simple definition:

````
sqsHandleResponseFromSocket:
  handler: ./src/lambda.sqsHandleResponseFromSocket
  events:
    - sqs:
        arn: ${self:custom.AWS_RESPONSE_SQS_QUEUE_URL}
        batchSize: 10
````

**Comment by serg06** [comment]
> i just changed the order on the plugin import, serverless-offline-sqs must come AFTER serverless-offline

That disables serverless-offline-sqs for me...
