### ISSUE TITLE
start:init hook is not triggered in sqs-offline plugin

### ISSUE THREAD

**Issue by Maxwell2022** [godu/serverless#7]
it looks like the `before:offline:start:init` hook is never triggered, not sure it has changed or not.

https://github.com/godu/serverless/blob/master/packages/serverless-offline-sqs/src/index.js#L37

Changing this to `before:offline:start` is actually working

**Comment by Maxwell2022** [comment]
@godu ^^

**Comment by Limess** [comment]
This works for me when running `serverless offline start` rather than `serverless offline`:

see https://github.com/dherault/serverless-offline#usage-with-serverless-offline-and-serverless-webpack-plugin

**Comment by Maxwell2022** [comment]
YES! that was it, thanks a lot to point this out!
I cannot believe that it worked perfectly for months without this `start` options...
