### ISSUE TITLE
ECONNREFUSED 0.0.0.0:9324

### ISSUE THREAD

**Issue by pkout** [godu/serverless#9]
Hi,

I get this error when running `serverless offline` with this plugin turned on:

```
(node:54160) UnhandledPromiseRejectionWarning: Error: connect ECONNREFUSED 0.0.0.0:9324
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1113:14)
(node:54160) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
```

Any idea why this is happening? Thanks!

**Comment by Maxwell2022** [comment]
are you running it in Docker? can you share your docker-compose and serverless.yml?

**Comment by pkout** [comment]
I am not using Docker for this. Should I create a demo project, zip it up and post it here?

**Comment by Maxwell2022** [comment]
how do you run elasticMQ then?
https://github.com/godu/serverless/tree/master/packages/serverless-offline-sqs#sqs

**Comment by pkout** [comment]
Ah, I don't. This is the problem. I thought that the plugin starts its own queue, but it uses ElasticQueue instead. I'll have to set that up. Thank you and sorry about this! Hopefully it will help someone in the future.

**Comment by Maxwell2022** [comment]
@pkout If you don't want to spend hours setting it up, just install docker and use the docker compose in the example: https://github.com/godu/serverless/tree/master/packages/serverless-offline-sqs/example

**Comment by pkout** [comment]
Will do. Thanks for the tip!
